# Generated by Django 6.0.3 on 2026-04-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otptoken_attempts_otptoken_otp_lookup_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='FavouriteLocation',
        ),
        migrations.DeleteModel(
            name='RecommendationHistory',
        ),
    ]
